### ISSUE TITLE
Export as LaTeX

### ISSUE THREAD

**Issue by 89netraM** [datx02-21-16/datx02#80]
I'm taking DAT060 now and found this tool super useful. Thank you!

One thing I wish for though is the possibility to, when done with a proof, export it as LaTeX source. That way I can include it, nicely formatted, in my notes or hand in.

If this is something you think the project could benefit from, I'd be more than happy to work on it.

**Comment by axelf4** [comment]
Yes, it would make a good inclusion. Feel free to ask about anything that is unclear.
